# Generated by Django 5.1.1 on 2024-10-01 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='post1',
            new_name='Post',
        ),
    ]
