# Generated by Django 5.1.1 on 2024-10-02 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0004_post_updated_at_alter_post_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
