# Generated by Django 5.1.1 on 2024-10-02 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0005_remove_post_image_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
