# Generated by Django 5.1.1 on 2024-10-02 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0007_alter_post_media'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='media',
            new_name='image',
        ),
    ]
