# Generated by Django 5.1.1 on 2024-10-02 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0012_remove_post_files_post_image_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
