# Generated by Django 5.1.1 on 2024-10-02 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0013_alter_post_image_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
